[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

authors = ["Jake Hillion <jake@hillion.co.uk>"]

[workspace.metadata.crane]
name = "testenv"

[workspace.dependencies]
thiserror = "2.0.12"
flate2 = "1.1.1"
anyhow = "1.0.98"
