[package]
name = "testenv-attrs"

proc_macro = true

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = { workspace = true }
