[package]
name = "testenv"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
thiserror = { workspace = true }
flate2 = { workspace = true }
anyhow = { workspace = true }
