[package]
name = "testenv-example"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

[dev-depdencies]
testenv = { path = "../testenv", features = ["attrs"] }
