name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Nix format and flake check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@a7ad9c4f0c65208097f4d34f3cfa1913b80cce5c # main

      - name: Check Nix formatting
        run: nix fmt

      - name: Run Nix flake check
        run: nix flake check

