name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Nix format and flake check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check Nix formatting
        run: nix fmt

      - name: Run Nix flake check
        run: nix flake check

