name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Nix format and flake check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@00199f951aeb9404028a6e4b95ad42546f73296a # main

      - name: Check Nix formatting
        run: nix fmt

      - name: Run Nix flake check
        run: nix flake check

